// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication6.Models;

#nullable disable

namespace WebApplication6.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240116183714_inIt")]
    partial class inIt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication6.Models.agent", b =>
                {
                    b.Property<int>("reactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reactionID"));

                    b.Property<string>("disc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("longName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("shortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("reactionID");

                    b.ToTable("agent");
                });

            modelBuilder.Entity("WebApplication6.Models.alergic", b =>
                {
                    b.Property<int>("drugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("drugID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("disc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("drugID");

                    b.ToTable("alergicsym");
                });

            modelBuilder.Entity("WebApplication6.Models.antialergy", b =>
                {
                    b.Property<int>("antidrugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("antidrugID"));

                    b.Property<string>("disc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("longName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("shortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("antidrugID");

                    b.ToTable("antialergy");
                });

            modelBuilder.Entity("WebApplication6.Models.drug", b =>
                {
                    b.Property<int>("drugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("drugID"));

                    b.Property<string>("analyse")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("disc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("longName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("shortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("drugID");

                    b.ToTable("drugs");
                });

            modelBuilder.Entity("WebApplication6.Models.employe", b =>
                {
                    b.Property<int>("empID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datejoin")
                        .HasColumnType("datetime2");

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("designationn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("empID");

                    b.ToTable("employes");
                });

            modelBuilder.Entity("WebApplication6.Models.registration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Confirmpwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("regist");
                });

            modelBuilder.Entity("WebApplication6.Models.usagecs", b =>
                {
                    b.Property<int>("drugcondID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("drugcondID"));

                    b.Property<string>("disc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("otherdetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("drugcondID");

                    b.ToTable("usages");
                });
#pragma warning restore 612, 618
        }
    }
}
